import { Product } from './types'

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Wireless Headphones',
        description: 'High-quality wireless headphones with noise cancellation',
        price: 19999.99,
        image: '/images/product-listings/headphone-03.png',
        category: 'Electronics',
        rating: 4.5,
        reviews: 120,
    },
    {
        id: '2',
        name: 'Smart Watch',
        description: 'Feature-rich smartwatch with health monitoring',
        price: 24999.99,
        image: '/images/product-listings/smart-watch.png',
        category: 'Electronics',
        rating: 4.2,
        reviews: 85,
    },
    {
        id: '3',
        name: 'Running Shoes',
        description: 'Comfortable running shoes with great support',
        price: 18999.99,
        image: '/images/product-listings/running-shoes.png',
        category: 'Sports',
        rating: 4.7,
        reviews: 210,
    },
    {
        id: '4',
        name: 'Backpack',
        description: 'Durable backpack for school or travel',
        price: 14999.99,
        image: '/images/product-listings/back-pack-1.png',
        category: 'Accessories',
        rating: 4.3,
        reviews: 50,
    },
    {
        id: '5',
        name: 'Adjustable Standing Fan',
        description: 'Energy-efficient portable standing fan for home use',
        price: 16999.99,
        image: '/images/product-listings/fan-03.png',
        category: 'Home Appliances',
        rating: 4.1,
        reviews: 30,
    },
    {
        id: '6',
        name: 'Fitted Shirt',
        description: 'Stylish fitted shirt for formal occasions',
        price: 2999.99,
        image: '/images/product-listings/fitted-shirt-03.png',
        category: 'Clothing',
        rating: 4.4,
        reviews: 60,
    },
    {
        id: '7',
        name: 'Wireless Headphones',
        description: 'Another model of high-quality wireless headphones',
        price: 17999.99,
        image: '/images/product-listings/headphone-02.png',
        category: 'Electronics',
        rating: 4.3,
        reviews: 90,
    },
    {
        id: '8',
        name: 'iPhone',
        description: 'Latest model iPhone with advanced features',
        price: 899999.99,
        image: '/images/product-listings/iPhone-02.png',
        category: 'Electronics',
        rating: 4.8,
        reviews: 500,
    },
    {
        id: '9',
        name: 'Polo Shirt',
        description: 'Classic polo shirt for casual wear',
        price: 2499.99,
        image: '/images/product-listings/polo-shirt-01.png',
        category: 'Clothing',
        rating: 4.2,
        reviews: 40,
    },
    {
        id: '10',
        name: 'Alienware Laptop',
        description: 'High-performance gaming laptop',
        price: 1499999.99,
        image: '/images/product-listings/laptop-alienware.png',
        category: 'Electronics',
        rating: 4.9,
        reviews: 200,
    },
    {
        id: '11',
        name: 'Lenovo Laptop',
        description: 'Reliable laptop for business or personal use',
        price: 449999.99,
        image: '/images/product-listings/laptop-lenovo.png',
        category: 'Electronics',
        rating: 4.4,
        reviews: 150,
    },
    {
        id: '12',
        name: 'Samsung Standing Freezer',
        description: 'Large capacity standing freezer for home use',
        price: 749999.99,
        image: '/images/product-listings/freezer-samsung-standing.png',
        category: 'Home Appliances',
        rating: 4.6,
        reviews: 100,
    },
    {
        id: '13',
        name: 'HP Laptop',
        description: 'Versatile laptop for everyday tasks',
        price: 549999.99,
        image: '/images/product-listings/laptop-hp.png',
        category: 'Electronics',
        rating: 4.3,
        reviews: 120,
    },
    {
        id: '14',
        name: 'Samsung Phone',
        description: 'Feature-packed smartphone with advanced camera',
        price: 899999.99,
        image: '/images/product-listings/samsung-02.png',
        category: 'Electronics',
        rating: 4.7,
        reviews: 300,
    },
    {
        id: '15',
        name: 'Pack of T-Shirts',
        description: 'Bundle of five comfortable T-Shirts',
        price: 24999.99,
        image: '/images/product-listings/t-shirt-pack.png',
        category: 'Clothing',
        rating: 4.5,
        reviews: 80,
    },
    {
        id: '16',
        name: 'Oster Blender',
        description: 'Oster Pro 1200 Blender with Professional Tritan Jar and Food Processor Attachment, Metallic Grey',
        price: 22999.99,
        image: '/images/product-listings/blender.png',
        category: 'Home Appliances',
        rating: 4.0,
        reviews: 367,
    }

    // Add more products as needed
]